name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.PUBLISH_CONTAINER}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wax:$(date +%s)
    - name: Push the Docker image
      run: docker push wax:$(date +%s)